package com.bt.base.model

enum class BtExceptionCode(val code: Int) {

    BTCODE_DATA_NULL(0),
    BTCODE_DATA_EMPTY(0),
    BTCODE_DATA_NULL_OR_EMPTY(0),

    BTCODE_INPUT_NULL(0),
    BTCODE_INPUT_EMPTY(0),
    BTCODE_INPUT_NULL_OR_EMPTY(0),
    BTCODE_INPUT_SHORT(0),
    BTCODE_INPUT_LONG(0),

    BTCODE_PARAM_NULL(0),
    BTCODE_PARAM_EMPTY(0),
    BTCODE_PARAM_NULL_OR_EMPTY(0),

    BTCODE_NETWORK_NO_CONNECTION(0),
    BTCODE_NETWORK_TIMEOUT(0),
    BTCODE_NETWORK_BAD_REQUEST(0),

    BTCODE_APP_FORCE_UPDATE(0),
    BTCODE_APP_SERVER_MAINTENANCE(0),
    BTCODE_APP_UNAUTHORIZED(0),
    BTCODE_APP_LOGIN_FAIL(0)
}
